services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    tty: true
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    healthcheck:
      test: ollama list || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    environment:
      - OLLAMA_DEBUG=1
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    networks:
      - ollama_network
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
      - shared-data:/shared
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: pgvector
    environment:
      - 'POSTGRES_DB=core'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    networks:
      - ollama_network
    volumes:
      - pgvector-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - 'DATASOURCE_URL=${DATASOURCE_URL:-jdbc:postgresql://pgvector:5432/core}'
      - 'DATASOURCE_USERNAME=${POSTGRES_USER:-admin}'
      - 'DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-admin}'
      - 'MAX_FILE_SIZE=${MAX_FILE_SIZE:-100MB}'
      - 'OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434/}'
      - 'AI_OLLAMA_EMBEDDING_OPTIONS_MODEL=${AI_OLLAMA_EMBEDDING_OPTIONS_MODEL:-nomic-embed-text:latest}'
      - 'OLLAMA_CHAT_MODEL=${OLLAMA_CHAT_MODEL:-llama3.1:latest}'
      - 'OLLAMA_CHAT_TEMPERATURE=${OLLAMA_CHAT_TEMPERATURE:-0.5}'
    depends_on:
      - pgvector
    networks:
      - ollama_network
    volumes:
      - backend-logs:/app/logs
      - shared-data:/shared

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge

volumes:
  pgvector-data:
  backend-logs:
  shared-data:
  ollama: