version: '3.8'
services:
  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama
    environment:
      - OLLAMA_DEBUG=1
    ports:
      - "11434:11434"
    healthcheck:
      test: ollama --version || exit 1
    entrypoint: [ "sh", "/usr/local/bin/init.sh.sh" ]
    volumes:
      - ./init.sh.sh:/usr/local/bin/init.sh.sh
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=core'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'